/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RboBaseInput {
        "label": string;
        "name": string;
        "type": "text" | "password" | "number";
    }
    interface RboForm {
        "onSubmit": Function;
    }
}
declare global {
    interface HTMLRboBaseInputElement extends Components.RboBaseInput, HTMLStencilElement {
    }
    var HTMLRboBaseInputElement: {
        prototype: HTMLRboBaseInputElement;
        new (): HTMLRboBaseInputElement;
    };
    interface HTMLRboFormElement extends Components.RboForm, HTMLStencilElement {
    }
    var HTMLRboFormElement: {
        prototype: HTMLRboFormElement;
        new (): HTMLRboFormElement;
    };
    interface HTMLElementTagNameMap {
        "rbo-base-input": HTMLRboBaseInputElement;
        "rbo-form": HTMLRboFormElement;
    }
}
declare namespace LocalJSX {
    interface RboBaseInput {
        "label"?: string;
        "name": string;
        "type"?: "text" | "password" | "number";
    }
    interface RboForm {
        "onSubmit"?: Function;
    }
    interface IntrinsicElements {
        "rbo-base-input": RboBaseInput;
        "rbo-form": RboForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rbo-base-input": LocalJSX.RboBaseInput & JSXBase.HTMLAttributes<HTMLRboBaseInputElement>;
            "rbo-form": LocalJSX.RboForm & JSXBase.HTMLAttributes<HTMLRboFormElement>;
        }
    }
}
