/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormInputChangeEvent, FormSubmittedEvent, } from "./events";
export namespace Components {
    interface RboButton {
        "disabled": boolean;
        "text": string;
    }
    interface RboCurrencyInput {
        "currency": string;
        "disabled": string;
        "label": string;
        "name": string;
        "required": string;
    }
    interface RboForm {
    }
}
declare global {
    interface HTMLRboButtonElement extends Components.RboButton, HTMLStencilElement {
    }
    var HTMLRboButtonElement: {
        prototype: HTMLRboButtonElement;
        new (): HTMLRboButtonElement;
    };
    interface HTMLRboCurrencyInputElement extends Components.RboCurrencyInput, HTMLStencilElement {
    }
    var HTMLRboCurrencyInputElement: {
        prototype: HTMLRboCurrencyInputElement;
        new (): HTMLRboCurrencyInputElement;
    };
    interface HTMLRboFormElement extends Components.RboForm, HTMLStencilElement {
    }
    var HTMLRboFormElement: {
        prototype: HTMLRboFormElement;
        new (): HTMLRboFormElement;
    };
    interface HTMLElementTagNameMap {
        "rbo-button": HTMLRboButtonElement;
        "rbo-currency-input": HTMLRboCurrencyInputElement;
        "rbo-form": HTMLRboFormElement;
    }
}
declare namespace LocalJSX {
    interface RboButton {
        "disabled"?: boolean;
        "text"?: string;
    }
    interface RboCurrencyInput {
        "currency"?: string;
        "disabled"?: string;
        "label"?: string;
        "name": string;
        "onFormInputChangeEvent"?: (event: CustomEvent<FormInputChangeEvent>) => void;
        "required"?: string;
    }
    interface RboForm {
        "onFormSubmittedEvent"?: (event: CustomEvent<FormSubmittedEvent>) => void;
    }
    interface IntrinsicElements {
        "rbo-button": RboButton;
        "rbo-currency-input": RboCurrencyInput;
        "rbo-form": RboForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rbo-button": LocalJSX.RboButton & JSXBase.HTMLAttributes<HTMLRboButtonElement>;
            "rbo-currency-input": LocalJSX.RboCurrencyInput & JSXBase.HTMLAttributes<HTMLRboCurrencyInputElement>;
            "rbo-form": LocalJSX.RboForm & JSXBase.HTMLAttributes<HTMLRboFormElement>;
        }
    }
}
