/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormInputChangeEvent, } from "./events";
export namespace Components {
    interface RboCurrencyInput {
        "currency": string;
        "isDisabled": boolean;
        "isRequired": string;
        "label": string;
        "name": string;
    }
    interface RboForm {
    }
}
declare global {
    interface HTMLRboCurrencyInputElement extends Components.RboCurrencyInput, HTMLStencilElement {
    }
    var HTMLRboCurrencyInputElement: {
        prototype: HTMLRboCurrencyInputElement;
        new (): HTMLRboCurrencyInputElement;
    };
    interface HTMLRboFormElement extends Components.RboForm, HTMLStencilElement {
    }
    var HTMLRboFormElement: {
        prototype: HTMLRboFormElement;
        new (): HTMLRboFormElement;
    };
    interface HTMLElementTagNameMap {
        "rbo-currency-input": HTMLRboCurrencyInputElement;
        "rbo-form": HTMLRboFormElement;
    }
}
declare namespace LocalJSX {
    interface RboCurrencyInput {
        "currency"?: string;
        "isDisabled"?: boolean;
        "isRequired"?: string;
        "label"?: string;
        "name": string;
        "onFormInputChangeEvent"?: (event: CustomEvent<FormInputChangeEvent>) => void;
    }
    interface RboForm {
    }
    interface IntrinsicElements {
        "rbo-currency-input": RboCurrencyInput;
        "rbo-form": RboForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rbo-currency-input": LocalJSX.RboCurrencyInput & JSXBase.HTMLAttributes<HTMLRboCurrencyInputElement>;
            "rbo-form": LocalJSX.RboForm & JSXBase.HTMLAttributes<HTMLRboFormElement>;
        }
    }
}
